gwillem/magento-malware-scanner

indicators.md
I've added a link to more analysis/intel. surrounding these indicators to indicators.md.
=> Added link to more intel. to indicators.md

composer.json
In order to use this library in the PHP projects, and pull it via package manager, added composer.json file.
=> Added composer.json for ability to use library via Composer.

.gitignore, README.md, docs/howto.md, malware/backend/4c4b3d4ba5bce7191a5138efa2468679, malware/backend/6eb201737a6ef3c4880ae0b8983398a9, malware/backend/d201d61510f7889f1a47257d52b15fa2, rules/backend.yar
Some small changes in the readme to cover the repo name change. I added a first setup of documentation and some samples / rules.
=> Documentation and malware

analysis/indicators.md
I originally added a link to the wrong incident in ThreatConnect and have updated the link.
=> Updated the ThreatConnect Link

mwscan/mwscan.py, mwscan/tests/fixtures/files/im_a_symlink
=> Don't follow symlinks

malware/backend/885677eac9af34318df5c8db66b3f5d6, rules/backend.yar, rules/frontend.yar
=> Added fake ebizmart payment harvester

mwscan/scan.py, mwscan/tests/test_mwscan.py, mwscan/tests/test_ruleset.py
=> Fix suppression of all output with --quiet 

corpus/backend/b62434979f1f15002bfb3c7cb2853d04, corpus/backend/b8b27ca1d1fd8188531d6c35b0581faa, rules/backend.yar
Posted more details in the security channel. This is from a hack which has compromised a serious number of Magento sites last night. Any site with the vulnerable Cart2Quote controller it seems is being affected, as the script is scanning IP addresses and dropping the malware laden Mage.php file into place, breaking a lot of EE sites.
=> Add malware payload and attack vector used to install infected file

mwscan/scan.py, mwscan/tests/test_mwscan.py
=> Remove newer_than file collection

build/all-confirmed.txt, build/all-confirmed.yar, corpus/backend/25201d4142d5b2ddd507ad84819c2810, rules/backend.txt
```
$ echo "UGFrIEhheG9y" | base64 -d 
Pak Haxor
```
=> Pak Haxor upload script

mwscan/scan.py
You can enable it using the `-c` or `--checksum` argument.
=> Added feature to show SHA1 checksum for matches

build/all-confirmed.txt, build/all-confirmed.yar, corpus/backend/9b4d4d6da504047df2f03addbe6ff99d, rules/backend.txt
This is not the actual malware or backdoor... So I'm not sure whether it belong here?
=> 404-page file upload script

mwscan/scan.py
My media dir was not being scanned as it was a symlink. Added an option so these are now scanned.
=> Add setting to allow following of symlinks

build/all-confirmed.txt, build/all-confirmed.yar, corpus/backend/f71ad06982064b125d155b6f601198b8, rules/backend.txt
This script is used for sending spam. I found this script at a `errors/503.php` page within a Magento installation.
I think this script is ~potentially dangerous~ an indicator the magento installation is compromised, and is (hopefully) not used in production by merchants or administrators. I could not find any legitiem usage of this script on Github or Google.
=> Pro mailer v2

build/all-confirmed.txt, build/all-confirmed.yar, corpus/backend/aa0e50f3e5e49a919004774f879546d0, rules/backend.txt
A script which will inject payment leaking code into corefiles.
This regex should match this inject script, but also the injected files.
=> base64 encoded cookie-content mailing

build/all-confirmed.txt, build/all-confirmed.yar, corpus/backend/f3b996f5c45f88192bcdc6d937a1d545, rules/backend.txt
If postdata contains one of `billing|firstname|cc_number|login|username|payment|cc_root` it will serialise the post data, base64 encode it, and sent it to magescripts.info using curl using the php exec method. This will show curl process in the processlist of the server with base64 encoded data to magescripts.info.
=> Base64 serialized postdata

.travis.yml
Would fix #149 :crossed_fingers:
=> Test upload of rules by Travis

mwscan/ruleset.py
=> Fix compatibility issue with py26 (CentOS)

corpus/backend/bd5b2e80555ea7f569a1e18095c0d494, corpus/frontend/be09ef55459f16cd2213abe192d4b1da, rules/backend.txt, tools/ctimer.py
=> Add backlinks-spam link poster via #199

rules/burner-domains.txt
https://www.flashpoint-intel.com/blog/compromised-magento-sites-delivering-malware/
Closes #198
=> Added burner domain as discovered by Flashpoint

.gitignore, mwscan/ruleset.py
=> Fix unicode vs utf8 problem with magesec ruleset

rules/burner-domains.txt
Received a malware snippet that posts credit card details to an endpoint on brewtees.com
=> Add burner domain

rules/frontend.txt
Found an additional endpoint being used in the same malware that is/was posting to `brewtees.com/wp-admin/js/fabric.php`
=> Add compromised domain

CONTRIBUTING.md, corpus/whitelisted/node_modules/es5-ext/test/Array/from.js, mwscan/ruleset.py
Whitelisted false positive on node_modules/es5-ext JS file 
Also added instructions about contributing a whitelisting.
=> Whitelisted es5-ext JS file

rules/backend.txt, rules/suspicious.yar
eg https://www.endclothing.com/eclubduuydyysdtauyxaucxzttue.js
=> Remove hex eval: FP

rules/backend.txt, rules/custom.yar, rules/frontend.txt, rules/suspicious.yar
It triggered on https://www.intersport.pl/media/js/fb4e0831f3a0cd7e0b113615ed35e85e.js:
```
function I(e, t, i) {
var n = Ie.exec(t);
return n ? Math.max(0, n[2] - (i || 0)) + (n[3] || 'px')  : t
}
```
=> Moved FP to suspicious.yar

rules/burner-domains.txt
=> Added exfil domains

rules/burner-domains.txt
gitformage.com and minifyscripts.com
=> added 2 burner domains

rules/burner-domains.txt
https://gist.github.com/gwillem/4370df130f85322f0749a1e2712a440f
=> add more domains

corpus/whitelisted/phpwcms/include/inc_module/mod_ads/inc/ads.fe_render.inc.php, corpus/whitelisted/phpwcms/include/inc_module/mod_ads/inc/ads.fe_render.inc.php-2008, corpus/whitelisted/phpwcms/include/inc_module/mod_ads/inc/ads_fe_init.inc.php, corpus/whitelisted/phpwcms/include/inc_module/mod_ads/inc/ads_fe_init.inc.php-2008
Origin files available here https://github.com/slackero/phpwcms/tree/master/include/inc_module/mod_ads/inc which belong to phpwcms
=>  Added whitelist for phpwcms

corpus/whitelisted/pma/libraries/sqlparser.lib.php-pma3.3.3, corpus/whitelisted/pma/libraries/sqlparser.lib.php-pma3.3.3-CRLF, corpus/whitelisted/pma/libraries/sqlparser.lib.php-pma3.3.8, corpus/whitelisted/pma/libraries/sqlparser.lib.php-pma3.4.3.1
This adds further versions of phpMyAdmin's sqlparser.lib.php as found
on customer installations.
=> Whitelist: Add more versions of sqlparser.lib.php

docs/usage.md
Just a documentation update to show a way to run the textual scan with grep via cron, and mail if a result is found
=> Add way to combine with mailx for hosted server cron usage

mwscan/ruleset.py
I'm no python programmer so those changes might be total rubbish, yet it fixed my problem described in #193
=> Fix handling of files with cached rulesets

rules/burner-domains.txt
=> added track-magento.com

rules/burner-domains.txt
References
* https://blog.malwarebytes.com/cybercrime/2019/05/skimmer-acts-as-payment-service-provider-via-rogue-iframe/
=> add skimming domains service iframes

rules/burner-domains.txt
References
* https://otx.alienvault.com/pulse/5ccc38ce6f8ff1d8fc18cc22
* https://blog.netlab.360.com/ongoing-credit-card-data-leak/
=> adding more magecart domains

rules/burner-domains.txt
References:
* https://www.fortinet.com/blog/threat-research/inter-skimmer-for-all.html
=> more skimming domains
